# Dependencies
markdown:         kramdown
gist:             gist

# Permalinks
permalink:        pretty

# Setup
title:            Sanjay Alwani
tagline:          'A Personal Portfolio'
description:      'Software developer'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Sanjay Alwani'
  url:            https://github.com/sanjayalwani
  email:          priv.sanjay+website@gmail.com

# paginate:         5

# Custom vars
version:          2.1.0

socials:
  github:         https://github.com/sanjayalwani/
  linkedin:       https://www.linkedin.com/in/sanjay-alwani/
  email:          priv.sanjay+website@gmail.com

plugins:
  - jekyll-gist
  # - jekyll-paginate
